image: python:3.6

stages:
  - test
  - deploy

test:
  stage: test
  script:
    # - apt-get update -qy
    # - apt-get install -y python3-pip
    - echo '***************************'
    - echo 'Instaling reqs'
    - pip3 install -r requirements.txt
    - echo '***************************'
    - echo 'Testing package'
    - python -m pytest --vcr-record=none tests/
    - echo '***************************'
    - echo 'Static security scan--pipeline will fail on medium/high severity'
    - bandit -c bandit.yml -ll -r .

  only:
  - merge_requests
  - pushes


deploy_to_pypi:
  stage: deploy
  script:
    - pip install twine wheel
    - python setup.py sdist bdist_wheel
    - twine upload --verbose dist/*
  only:
    - tags