image: python:3.6

stages:
  - build
  - test
  - deploy

test:
  stage: test
  script:
    # - apt-get update -qy
    # - apt-get install -y python3-pip
    - echo '***************************'
    - echo 'Instaling reqs'
    - pip3 install -r requirements.txt
    - echo '***************************'
    - echo 'Testing package'
    - python -m pytest tests/

  only:
  - merge_requests
  - pushes

docker:
  stage: deploy
  only: master
  script:
    - docker build . -t viderum/ckan-harvester-ng