language: python
python:
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install ".[test]" . # install package + test dependencies
  - pip3 install -r requirements.txt
script: 
    - python -m pytest --vcr-record=none tests/
    - bandit -c bandit.yml -ll -r .
after_success:
  - codecov # submit coverage
deploy:
    provider: pypi
    username: "$PYPI_USER"
    password: "$PYPI_PASSWORD"
    distributions: "sdist bdist_wheel"
    on:
        tags: true
